FORMAT: X-1A

HOST: https://secure.gooddata.com

#GoodData API reference has moved!

The standalone version of the GoodData API reference is no longer available. Use the embedded version at: https://developer.gooddata.com/api.

Don't worry, the embedded version has all of the functionality you're used to in the standalone version. It also features improved findability and navigability, more complete information, better JSON descriptions, faster loading time, and improved look-and-feel. 